site_name: Jetpack Compose
site_url: https://docs.compose.net.cn/


repo_name: 'Jetpack Compose 博物馆'
repo_url: 'https://github.com/Compose-Museum/Compose-Tutorial'
edit_uri: 'tree/main/docs/'

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.instant
  font:
    code: Jetbrains Mono
nav:
  - 'Jetpack Compose':
    - '概述': index.md
    - '在开始之前': start.md
    - '基本组件':
      - 'AlertDialog': elements/alertdialog.md
      - 'Button': elements/button.md
      - 'Card': elements/card.md
      - 'Text': elements/text.md
      - 'Icon': elements/icon.md
      - 'Image': elements/image.md
      - 'IconButton': elements/iconbutton.md
      - 'Surface': elements/surface.md
      - 'Slider': elements/slider.md
      - 'TextField': elements/textfield.md
    - '布局': 
      - '概述': layout/overview.md
      - 'Column': layout/column.md
      - 'ModalBottomSheetLayout': layout/modalbottomsheetlayout.md
      - 'Row': layout/row.md
      - 'Spacer': layout/spacer.md
      - 'Scaffold':
        - '概述': layout/scaffold/overview.md
        - '1. topBar': layout/scaffold/topbar.md
        - '2. bottomBar': layout/scaffold/bottombar.md
        - '3. drawerContent': layout/scaffold/drawercontent.md
        - '4. floatingActionButton': layout/scaffold/floatingactionbutton.md
      - '自定义Layout': layout/custom_layout.md
    - '手势':
      - 'Swipeable滑动': gesture/swipeable.md
    - '动画':
      - '概述': animation/overview.md
      - 'AnimationVisibility': animation/animationvisibility.md
    - '主题':
      - '初识 MaterialTheme': theme/meet_material_theme.md
      - '深入理解 MaterialTheme 与 CompositionLocal': theme/understanding_material_theme.md
      - '自定义你的主题方案': theme/custom_your_theme.md
    - '参数':
      - 'Modifier': parameters/modifier.md
    - '代码实验室': codelabs.md
    - '资源': resources.md
    - '关于贡献': contributing.md
    - '关于投喂': pay.md
  - 'API 文档':
    - '组件':
      - 'Text': api/elements/text.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Compose-Museum/Compose-Tutorial/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: date
